### ISSUE TITLE
the Chinese characters cannot be shown

### ISSUE THREAD

**Issue by zhanghao1988** [neuropsychology/Neuropsydia.py#19]
in  the choice.py, if the title is chinese, it would be shown as blank.

**Comment by DominiqueMakowski** [comment]
@zhanghao1988 thanks for pointing this out!

Mmmh... @LeoDutriaux, do you have any intuition about the cause of this issue? Do you think that this is an error due to the default font we use? an encoding problem? or a pygame's one?

**Comment by LeoDutriaux** [comment]
I think it's more likely to be a font problem, because utf8 supports chinese characters.

**Comment by DominiqueMakowski** [comment]
@LeoDutriaux it seems that you're right indeed, as there is an issue about our default font Roboto [not supporting chinese and japanese](https://github.com/podlove/podlove-subscribe-button/issues/110) characters.

@zhanghao1988 we need to either add an option within choice to change the `style` parameter (with which you can also control the font) or add a metaparameter to control the default font in the whole script. We'll try to have it done by the end of next week, we'll let you know!

Again, thanks for noticing this issue.

**Comment by DominiqueMakowski** [comment]
@zhanghao1988 I've managed to resolve this issue quicklier than expected. 

- Uninstall and re-download neuropsydia from its repo (`pip install https://github.com/neuropsychology/Neuropsydia.py/zipball/master`)
- There is now a new parameter in `choice`, called `choices_style`. 
- Put a font file that supports chinese characters (e.g., simsun.ttc) in your script folder. 
- Finally, set "simsun.ttc" for the `choices_style` parameter. It should work like a charm.

Let me know how it goes!

**Comment by zhanghao1988** [comment]
@DominiqueMakowski sorry, it didn't work in my computer. The error message is "simsun was not defined".  I think this may be a problem of pygame, for pygame is not well supportting Chinese.

**Comment by DominiqueMakowski** [comment]
@zhanghao1988 Looks like your script didn't find the simsun font. Could you try again after downloading the font I used from [here](https://mab.to/JIqYXAH1m), save it in the *same directory* where your script is. Within this script, set the `choices_style` parameter of the choice function to `choices_style="simsun.ttc"`. If that doesn't work, could you attach a screenshot of your script and of the error? 
Thanks!

**Comment by LeoDutriaux** [comment]
see https://github.com/neuropsychology/Neuropsydia.py/issues/24
