### ISSUE TITLE
Korean characters are not showing when using instruction, write.py

### ISSUE THREAD

**Issue by nuunuu** [neuropsychology/Neuropsydia.py#24]
In fact, all functions including text does not show any Korean characters.
I think it is similar issues with the Chinese characters does not show. 
I hope you to give options to choose font not only in choice.py but also every functions including text such as instruction, write, questionnaire.

And I also find out choices_style=' font.ttf' does not work in Korean font.

**Comment by DominiqueMakowski** [comment]
@LeoDutriaux Any idea if that's possible to address?

**Comment by LeoDutriaux** [comment]
Hi,
Sorry for the delay, I guess it's too late, but in case of somebody read it. There are different thing that you can do to solve the problem:
1) change both choices_style and title_style of the choice() function with the name of your font (e.g., font.ttf)
2) check that your font file is in the same folder as your python script. If not, you can put the path of the font in choices_style and title_style instead.
3) If none this doesn't work, I have added a new argument in all the function involving text: characters. If characters = 'cjk', then the function will use a font supporting a varieties of non-latin characters.

**Comment by Tam-Pham** [comment]
Hi @LeoDutriaux, 

I tried to add the Chinese characters to my instructions, as below:
```
n.instructions("你好 In this task, you will be presented with different images and your task is to rate how intense your feeling is when you see the images.", non_latin=True)
```
However, it doesn't seem to work yet
![test n instructions()](https://user-images.githubusercontent.com/47100701/71060139-adf12480-219f-11ea-8e7a-7cdf98cca6e6.png)

**Comment by LeoDutriaux** [comment]
Hi @Tam-Pham ,
I just tried the exact same command on my computer and it works fine.
Is the problem only with `instructions` or with `write` too for instance?

**Comment by LeoDutriaux** [comment]
![Screenshot 2019-09-16 12 22 28](https://user-images.githubusercontent.com/11191423/71075573-935d8200-2184-11ea-8097-9d3418185300.png)

**Comment by LeoDutriaux** [comment]
From your screenshot it looks like `instructions` used  'RobotoBlack.ttf'  or 'RobotoBold.ttf' for the font of the text, which is weird as it should use 'RobotoRegular.ttf' by default, I'm not sure where it could come from...

**Comment by DominiqueMakowski** [comment]
maybe the font has not been properly downloaded? @Tam-Pham could you check if the font has been downloaded and is in the package (python/site-packages/etc)

**Comment by LeoDutriaux** [comment]
You're right @DominiqueMakowski , the fonts are not downloading from github. Maybe because they are too heavy (16MB each, and they are 4)? Any other idea why?

**Comment by DominiqueMakowski** [comment]
hold on, is the format of the font ttf? It seems like all extra-code stuff that has to be imported with the package has to be specified here:

https://github.com/neuropsychology/Neuropsydia.py/blob/5cad4a3846576ac75aa3bed6616a55c4eee25850/setup.py#L20-L23

**Comment by LeoDutriaux** [comment]
That was indeed the problem, it should work now!

**Comment by LeoDutriaux** [comment]
UPDATE: the `non_latin` argument is now obsolete. Please use `characters = 'cjk'` instead if you want to use chinese, japanese, or korean characters.This will allow the implementation of other writing systems in the futur.

**Comment by LeoDutriaux** [comment]
Can we close the issue?

**Comment by Tam-Pham** [comment]
It works perfectly now!

![image](https://user-images.githubusercontent.com/47100701/71168317-5d59f400-2291-11ea-90e6-eac1d0cd8fd5.png)

Much thanks, Leo!

**Comment by LeoDutriaux** [comment]
Great! How the style  of the font looks like to you? Does it look cool? Formal? 
The other option would be this one https://www.google.com/get/noto/#serif-hant
What do you think?
