### ISSUE TITLE
ask() inconsistently works after backspacing

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/Neuropsydia.py#7]
when writing something with `ask()`, then erasing it with backspace, then re-writing it, sometimes it doesn't work.

**Comment by LeoDutriaux** [comment]
It already happened to me, was it with number as allowable ?

**Comment by DominiqueMakowski** [comment]
I don't know really... we have to find a way to consistently reproduce this error and print what it returns when we press ENTER

**Comment by LeoDutriaux** [comment]
I tried, but it is not consistent...

**Comment by DominiqueMakowski** [comment]
I've reproduced this bug, it happens when typing a F key (e.g., F11), and then backspacing it. I think the F keys somehow break the thing...
